[project]
name = "softstack-backend"
version = "0.1.0"
description = "This is the Back-End project the Soft-Stack project."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "pydantic>=2.13.5",
    "pymongo>=4.18.2",
    "pyjwt>=2.10.1",
    "pwdlib[argon2]>=0.2.1",
    "uvicorn>=0.54.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.0",
]
